"""change columns type

Revision ID: 10600ad6ff97
Revises: f50676422726
Create Date: 2025-05-07 12:35:30.306442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10600ad6ff97'
down_revision: Union[str, None] = 'f50676422726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.add_column('hotels', sa.Column('capacity', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.drop_column('hotels', 'capasity')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.add_column('hotels', sa.Column('capasity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_column('hotels', 'capacity')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    # ### end Alembic commands ###
