"""change tables and add room table

Revision ID: d76bb817f9cd
Revises: 3ee3cfaec230
Create Date: 2025-05-13 12:07:40.712461

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d76bb817f9cd"
down_revision: Union[str, None] = "3ee3cfaec230"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("hotel_id", sa.Integer(), nullable=True),
        sa.Column(
            "type", sa.Enum("NA", "STANDARD", "LUX", name="room_type"), nullable=False
        ),
        sa.Column("price_per_night", sa.Float(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rooms_id"), "rooms", ["id"], unique=False)
    op.add_column("bookings", sa.Column("room_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "bookings", "rooms", ["room_id"], ["id"])
    op.drop_column("hotels", "base_price")
    op.drop_column("hotels", "capacity")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hotels",
        sa.Column("capacity", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "hotels",
        sa.Column(
            "base_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.drop_column("bookings", "room_id")
    op.drop_index(op.f("ix_rooms_id"), table_name="rooms")
    op.drop_table("rooms")
    # ### end Alembic commands ###
